<?php
$form = array(
  array( 'group_name'=>'Ядро',
    'modules'=>array(
      array('sistem_name'=>'drupal',                            'name'=>'DRUPAL 7',                         'description'=>'Ядро' ),
    ),),
  array( 'group_name'=>'Администрирование',
    'modules'=>array(
      array('sistem_name'=>'admin_menu',                        'name'=>'Administration menu',              'description'=>'удобное выпадающее меню администратора, заменяет стандартное' ),
      array('sistem_name'=>'backup_migrate',                    'name'=>'Backup and Migrate',               'description'=>'Модуль делает резервные копии БД, возможно функционал шире' ),
      array('sistem_name'=>'module_filter',                     'name'=>'Module Filter',                    'description'=>'Расширяет функционал страницы с модулями Drupal\'a.<br>На любителя' ),
    ),),
  array( 'group_name'=>'Блоки',
    'modules'=>array(
      array('sistem_name'=>'block_class',                       'name'=>'Block Class',                      'description'=>'Добавляет возможность добавить класс блокам' ),
      array('sistem_name'=>'imageblock',                        'name'=>'Image Block',                      'description'=>'Позволяет выводить в блоке изображение' ),
      array('sistem_name'=>'menu_block',                        'name'=>'Menu block',                       'description'=>'Добавляет возможность вывести меню с любого пункта в виде блока' ),
      array('sistem_name'=>'blockgroup',                        'name'=>'Block Group',                      'description'=>'Позволяет группировать блоки' ),
    ),),
  array( 'group_name'=>'Веб форма', 'group_class'=>'webform',
    'modules'=>array(
      array('sistem_name'=>'webform',                           'name'=>'Webform',                          'description'=>'Модуль Webform позволяет создавать формы с различными типами полей: дата, текстовое поле, файл и т.д. Кроме добавления неограниченного количества разнообразных полей в форму, модуль Webform позволяет создавать пошаговые формы.' ),
      array('sistem_name'=>'webform_ajax',                      'name'=>'Webform Ajax',                     'description'=>'Модуль Webform Ajax добавляет веб-формам поддержку техники AJAX. Установив этот модуль, с использованием AJAX можно отправлять веб-формы и перемещаться между страницами по веб-форме, которая использует несколько шагов. Всё это улучшает эргономику, делает форму более быстрой (передаётся меньшее количество данных) и снижает нагрузку на сервер.' ),
      array('sistem_name'=>'webform_validation',                'name'=>'Webform Validation',               'description'=>'Модуль Webform Validation добавляет в документ веб-формы вкладку, которая позволяет задать правила проверки используемых веб-формой компонентов.' ),
      array('sistem_name'=>'webform_mysql_views',               'name'=>'Webform MySQL Views',              'description'=>'Модуль Webform MySQL Views позволяет выводить в видах данные, которые были получены модулем Webform. Эти виды могут быть удобны в том случае, когда вы нуждаетесь в автоматическом доступе к этим данных из внешних приложений без экспорта, импорта или используете АПИ на основе веба.' ),
      array('sistem_name'=>'webform_report',                    'name'=>'Webform Report',                   'description'=>'Модуль Webform Report позволяет создавать простые, динамические отчёты на основе данных собранных модулем Webform. Он добавляет новый тип документов, который содержит критерии отчёта, а показываемые данные обновляются автоматически, сразу после отправки веб-формы. Данные отчёта могут быть отсортированы в зависимости от предпочтений читающего этот отчёт человека, без изменения критериев составления отчёта.' ),
      array('sistem_name'=>'webform_rules',                     'name'=>'Webform Rules',                    'description'=>'Модуль Webform Rules добавляет правила для работы с веб-формами. Если вы когда-нибудь искали правило, которое должно выполняться после отправки веб-формы и не могли найти его, попробуйте поставить этот модуль, возможно он решит эту проблему.' ),
    ),),
  array( 'group_name'=>'Дополнительные',
    'modules'=>array(
      array('sistem_name'=>'ctools',                            'name'=>'Chaos tool suite (ctools)',        'description'=>'описание отсутствует' ),
      array('sistem_name'=>'token',                             'name'=>'Token',                            'description'=>'описание отсутствует' ),
      array('sistem_name'=>'libraries',                         'name'=>'Libraries API',                    'description'=>'описание отсутствует' ),
      array('sistem_name'=>'entity',                            'name'=>'Entity API',                       'description'=>'описание отсутствует' ),
      array('sistem_name'=>'jquery_update',                     'name'=>'jQuery Update',                    'description'=>'описание отсутствует' ),
      array('sistem_name'=>'cck',                               'name'=>'Content Construction Kit (CCK)',   'description'=>'описание отсутствует' ),
      array('sistem_name'=>'entityreference',                   'name'=>'Entity reference',                 'description'=>'описание отсутствует' ),
      array('sistem_name'=>'transliteration',                   'name'=>'Transliteration',                  'description'=>'описание отсутствует' ),
      array('sistem_name'=>'variable',                          'name'=>'Variable',                         'description'=>'описание отсутствует' ),
    ),),
  array( 'group_name'=>'Карты и геоданные',
    'modules'=>array(
      array('sistem_name'=>'location',                          'name'=>'Location',                         'description'=>'Поле для хранения геокоординат. Виджет позволяет вводить как адрес, так и широту/долготу. В составе есть геокодер. Имеется интеграцию с Views. Форматер для вывода данных на карте отсутствует, поэтому модуль используется в основном в связке с GMap Module.' ),
      array('sistem_name'=>'gmap',                              'name'=>'GMap Module',                      'description'=>'Предоставляет интерфейс для работы с Google Maps API 2. Модуль имеет интеграцию с Location и позволяет указывать координаты с помощью клика на карте виджета. Доступен форматтер для вывода маркеров на карте. Имеет интеграцию с Views и может выводить несколько точек на одной карте по данным из поля Location.' ),
      array('sistem_name'=>'getlocations',                      'name'=>'Get Locations',                    'description'=>'Поле для хранения геокоординат и форматтер для их вывода на картах Google с помощью Google Maps API 3. Модуль позиционируется как современная альтернатива связке Location и GMap Module. Это делается либо с помощью геокодирования введённого адреса, либо с помощью перетаскивания дефолтной метки. Есть интеграция с Views.' ),
      array('sistem_name'=>'geofield',                          'name'=>'Geofield',                         'description'=>'Поле для хранения геоданных (точки, линии, полигоны и т.д.) и форматтер для их вывода на Google Map или любой карте, поддерживаемой OpenLayers. Из виджетов доступны: Well Known Text (WKT), Latitude / Longitude, GeoJSON, Bounds. Виджет с визуальным добавлением данных доступен с помощью модулей Leaflet Widget или Geofield Gmap. Встроенного геокодера нет, но есть интеграция с модулем Geocoder. Интеграция с Views с помощью подмодуля Geofield Map.' ),
      array('sistem_name'=>'geofield_ymap',                     'name'=>'Geofield Yandex Maps',             'description'=>'Виджет, форматтер и views хэндлер для Geofield позволяющий вводить и выводить гео-объекты (точки, линии, полигоны) на Яндекс.Картах 2.1. Модуль так же позволяет использовать карты в своих формах и динамически генерировать карты с помощью PHP, HTML или Javascript.' ),
      array('sistem_name'=>'geolocation',                       'name'=>'Geolocation Field',                'description'=>'Поле для хранения геокоординат и форматтер для их вывода на карте Google. Вводить координаты можно как кликом на карте виджета, так и с помощью поиска. Интеграция с Views пока только в виде отдельного модуля.' ),
      array('sistem_name'=>'yamaps',                            'name'=>'Yandex.Maps',                      'description'=>'Поле для хранения геоданных (точки, линии, полигоны, дороги), виджет для визуального добавления данных и форматтер для их вывода на карте Яндекс. Модуль довольно странный, например для ввода точки надо кликнуть на карте, в появившейся форме ввести заголовок маркера, текст балуна, выбрать цвет и нажать кнопку Save (скриншот). Пользователю доступны сразу все инструменты для ввода данных, без ограничения. Количество данных так же не ограничено. Хранятся все данные в формате json в одной единственной колонке, поэтому об Views можно даже не думать.' ),
      array('sistem_name'=>'gm3',                               'name'=>'Google Maps API V3',               'description'=>'Набор полей для хранения геоданных (точки, полигоны, линии, области), виджет для визуального добавления данных с помощью карт Google (скриншот) и форматтер для вывода данных на карте. Модуль крайне сырой.' ),
      array('sistem_name'=>'openlayers',                        'name'=>'OpenLayers',                       'description'=>'Набор модулей для интеграции Drupal с одноимённой javascript библиотекой. Библиотека представляет из себя мощный, но довольно сложный инструмент для работы с картами. В качестве карт можно использовать OpenStreetMap, Google Maps, Yahoo Maps и другие. Есть интеграция с Views.' ),
      array('sistem_name'=>'leaflet',                           'name'=>'Leaflet',                          'description'=>'Интеграция молодой javascript библиотеки для работы с картами — Leaflet. Модуль представляет из себя форматтер полей Geofield, выводящий данные на карте. Виджет для визуального ввода доступен в виде отдельного модуля. Есть интеграция с Views и возможность вывести несколько точек на одной карте. По умолчанию из карт доступна только OSM Mapnik, но есть возможность прикрутить Google Maps и Yandex Maps. Есть PHP API для лёгкого вывода карт.' ),
      array('sistem_name'=>'locationmap',                       'name'=>'Location Map',                     'description'=>'Небольшой модуль, создающий страницу с картой Google, на которой можно вывести информацию о расположении одного единственного объекта (скриншот). В настройках можно указать заголовок страницы, координаты объекта и его описание ' ),
      array('sistem_name'=>'simple_gmap',                       'name'=>'Simple Google Maps',               'description'=>'Форматтер для текстовых полей, позволяющий выводить карту Google с маркером по адресу, указанному в поле.'),
    ),),
  array( 'group_name'=>'Меню',
    'modules'=>array(
      array('sistem_name'=>'menu_attributes',                   'name'=>'Menu attributes',                  'description'=>'Добавляет возможность добавления разных атрибутов для пунктов меню' ),
      array('sistem_name'=>'taxonomy_menu',                     'name'=>'Taxonomy menu',                    'description'=>'Позволяет вывести термины таксономии в качестве пунктов меню' ),
    ),),
  array( 'group_name'=>'Поля',
    'modules'=>array(
      array('sistem_name'=>'date',                              'name'=>'Date',                             'description'=>'поле даты' ),
      array('sistem_name'=>'link',                              'name'=>'Link',                             'description'=>'поле ссылка' ),
      array('sistem_name'=>'email',                             'name'=>'Email Field',                      'description'=>'поле email' ),
      array('sistem_name'=>'addressfield',                      'name'=>'Address Field',                    'description'=>'поле для ввода адреса' ),
      array('sistem_name'=>'field_collection',                  'name'=>'Field collection',                 'description'=>'поле коллекция полей' ),
      array('sistem_name'=>'references',                        'name'=>'References (Node, User)',          'description'=>'поле ссылки на другой материал, пользователя' ),
      array('sistem_name'=>'autocreate',                        'name'=>'Autocreate Node Reference',        'description'=>'расширяет модуль References<br> автоматическое создание материала если он до этого небыл создан<br> описание возможно не корректное' ),
      array('sistem_name'=>'noderefcreate',                     'name'=>'Node Reference Create',            'description'=>'расширяет модуль References<br> автоматическое создание материала если он до этого небыл создан<br> описание возможно не корректное' ),
      array('sistem_name'=>'url',                               'name'=>'URL',                              'description'=>'описание отсутствует' ),
      array('sistem_name'=>'image_url_formatter',               'name'=>'Image URL Formatter',              'description'=>'вывод изображения в виде ссылки' ),
      array('sistem_name'=>'fancybox',                          'name'=>'fancyBox',                         'description'=>'Попап фансибокс, добавляет формат вывода для изображений и другое' ),
      array('sistem_name'=>'field_group',                       'name'=>'Field Group',                      'description'=>'группировка полей' ),
      array('sistem_name'=>'hierarchical_select',               'name'=>'Hierarchical Select',              'description'=>'Добавляет возможности к полям таксономии при добавлении/редактировании материала' ),
      array('sistem_name'=>'multiupload_filefield_widget',      'name'=>'Multiupload Filefield Widget',     'description'=>'мультизагрузка файлов' ),
      array('sistem_name'=>'multiupload_imagefield_widget',     'name'=>'Multiupload Imagefield Widget',    'description'=>'мультизагрузка изображений' ),
      array('sistem_name'=>'filefield',                         'name'=>'FileField',                        'description'=>'описание отсутствует' ),
      array('sistem_name'=>'lightbox2',                         'name'=>'Lightbox2',                        'description'=>'описание отсутствует' ),
    ),),
  array( 'group_name'=>'Перевод',
    'modules'=>array(
      array('sistem_name'=>'l10n_client',                       'name'=>'Localization client',              'description'=>'удобный интерфейс перевода Drupal' ),
      array('sistem_name'=>'l10n_update',                       'name'=>'Localization update',              'description'=>'автоматическое скачивание переводов модулей' ),
    ),),
  array( 'group_name'=>'Представление',
    'modules'=>array(
      array('sistem_name'=>'views',                             'name'=>'Views',                            'description'=>'модуль Views' ),
      array('sistem_name'=>'views_slideshow',                   'name'=>'Views Slideshow',                  'description'=>'добавляет возможность создавать слайдшоу во Views' ),
      array('sistem_name'=>'better_exposed_filters',            'name'=>'Better Exposed Filters',           'description'=>'расширяет функционал фильтров Views' ),
      array('sistem_name'=>'draggableviews',                    'name'=>'Draggableviews',                   'description'=>'добавляет возможность упорядочить вывод Views как хочет пользователь' ),
      array('sistem_name'=>'views_dependent_filters',           'name'=>'Views Dependent Filters',          'description'=>'описание отсутствует' ),
      array('sistem_name'=>'views_nivo_slider',                 'name'=>'Views Nivo Slider',                'description'=>'описание отсутствует' ),
    ),),
  array( 'group_name'=>'Разное',
    'modules'=>array(
      array('sistem_name'=>'rules',                             'name'=>'Rules',                            'description'=>'описание отсутствует' ),
      array('sistem_name'=>'panels',                            'name'=>'Panels',                           'description'=>'описание отсутствует' ),
      array('sistem_name'=>'similarterms',                      'name'=>'Similar By Terms',                 'description'=>'описание отсутствует' ),
      array('sistem_name'=>'auto_nodetitle',                    'name'=>'Automatic Nodetitles',             'description'=>'Автоматически создается заголовок материала, возможно необходимо повторное сохранение в некоторых случаях' ),
      array('sistem_name'=>'i18n',                              'name'=>'Internationalization',             'description'=>'описание отсутствует' ),
      array('sistem_name'=>'context',                           'name'=>'Context',                          'description'=>'описание отсутствует' ),
      array('sistem_name'=>'page_title',                        'name'=>'Page Title',                       'description'=>'описание отсутствует' ),
      array('sistem_name'=>'ds',                                'name'=>'Display Suite',                    'description'=>'описание отсутствует' ),
      array('sistem_name'=>'strongarm',                         'name'=>'Strongarm',                        'description'=>'описание отсутствует' ),
      array('sistem_name'=>'superfish',                         'name'=>'Superfish',                        'description'=>'описание отсутствует' ),
      array('sistem_name'=>'calendar',                          'name'=>'Calendar',                         'description'=>'Календарь, функционал не изучен до конца' ),
      array('sistem_name'=>'imagecache_actions',                'name'=>'ImageCache Actions',               'description'=>'описание отсутствует' ),
      array('sistem_name'=>'feeds',                             'name'=>'Feeds',                            'description'=>'модуль ипорта материалов' ),
      array('sistem_name'=>'media_youtube',                     'name'=>'Media: YouTube',                   'description'=>'описание отсутствует' ),
      array('sistem_name'=>'node_clone',                        'name'=>'Node clone',                       'description'=>'Позволяет создать копию материала, может не совсем корректно работать с модулем коллекция полей' ),
      array('sistem_name'=>'print',                             'name'=>'Printe',                           'description'=>'Позволяет создать страницы для печати' ),
      array('sistem_name'=>'modal_forms',                       'name'=>'Modal forms (with ctools)',        'description'=>'описание отсутствует' ),
    ),),
  array( 'group_name'=>'Тектсовые редакторы',
    'modules'=>array(
      array('sistem_name'=>'wysiwyg',                           'name'=>'Wysiwyg',                          'description'=>'продвинутый WYSIWYG редактор, удобен для копирования уже отформатированных текстов из офисных программ (типа Word или OpenOffice)' ),
      array('sistem_name'=>'ckeditor',                          'name'=>'CKEditor',                         'description'=>'Тектсовый редактор' ),
      array('sistem_name'=>'imce_wysiwyg',                      'name'=>'IMCE Wysiwyg bridge',              'description'=>'Тектсовый редактор' ),
      array('sistem_name'=>'geshifilter',                       'name'=>'GeSHi Filter',                     'description'=>'Подсветка синтаксиса' ),
      array('sistem_name'=>'bueditor',                          'name'=>'bueditor',                         'description'=>'простой WYSIWYG редактор, подойдет для большинства сайтов' ),
    ),),
  array( 'group_name'=>'Хлебные крошки',
    'modules'=>array(array('sistem_name'=>'path_breadcrumbs',                  'name'=>'Path Breadcrumbs',                 'description'=>'модуль, который умеет строить хлебные крошки для абсолютно любых страниц (как статичных, так и динамичных). Удобный интерфейс (частично слизан с page manager\'a) позволяет быстро и красиво строить навигационную линейку по крошкам. Модуль позволяет заменить все остальные для построения хлебных крошек.' ),
      array('sistem_name'=>'custom_breadcrumbs',                'name'=>'Custom Breadcrumbs',               'description'=>'Хлебные крошки' ),
      array('sistem_name'=>'panels_breadcrumbs',                'name'=>'Panel Breadcrumbs',                'description'=>'Хлебные крошки' ),
      array('sistem_name'=>'hansel',                            'name'=>'Hansel breadcrumbs',               'description'=>'Хлебные крошки' ),
    ),),
  array( 'group_name'=>'SEO',
    'modules'=>array(
      array('sistem_name'=>'pathauto',                          'name'=>'Pathauto',                         'description'=>'создает правила для синонимов ссылок' ),
      array('sistem_name'=>'metatag',                           'name'=>'Metatag',                          'description'=>'добавляет метатеги и позволяет их настроить' ),
      array('sistem_name'=>'xmlsitemap',                        'name'=>'XML sitemap',                      'description'=>'создает карту сайта XML' ),
      array('sistem_name'=>'redirect',                          'name'=>'Redirect',                         'description'=>'описание отсутствует' ),
      array('sistem_name'=>'globalredirect',                    'name'=>'Global Redirect',                  'description'=>'описание отсутствует' ),
    ),),
  array( 'group_name'=>'Интернет магазин',
    'modules'=>array(
      array('sistem_name'=>'ubercart',                          'name'=>'Ubercart',                           'description'=>'описание отсутствует' ),
      array('sistem_name'=>'uc_ajax_cart',                      'name'=>'Ubercart AJAX Cart',                 'description'=>'описание отсутствует' ),
      array('sistem_name'=>'uc_optional_checkout_review',       'name'=>'Ubercart Optional Checkout Review',  'description'=>'описание отсутствует' ),
    ),),

  /*array( 'group_name'=>'фффффффффффф',
    'modules'=>array(
      array('sistem_name'=>'фффффффф',                   'name'=>'фффффффффффф',                    'description'=>'фффффффф' ),
  ),),*/

);
